/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DataSourceForm: typeof import('./components/management/datasource/DataSourceForm.vue')['default']
    DataSourceManage: typeof import('./components/management/datasource/DataSourceManage.vue')['default']
    Editor: typeof import('./components/app/Editor.vue')['default']
    Header: typeof import('./components/app/Header.vue')['default']
    HeaderExtra: typeof import('./components/app/HeaderExtra.vue')['default']
    HeaderHero: typeof import('./components/app/HeaderHero.vue')['default']
    HeaderMenu: typeof import('./components/app/HeaderMenu.vue')['default']
    MainLayout: typeof import('./components/MainLayout.vue')['default']
    ManagementPanel: typeof import('./components/management/ManagementPanel.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTree: typeof import('naive-ui')['NTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/settings/SettingsPanel.vue')['default']
    SideMenu: typeof import('./components/app/SideMenu.vue')['default']
    Studio: typeof import('./components/develop/Studio.vue')['default']
    TemplateEditor: typeof import('./components/management/template/TemplateEditor.vue')['default']
    TemplateFileTree: typeof import('./components/management/template/TemplateFileTree.vue')['default']
    TemplateManage: typeof import('./components/management/template/TemplateManage.vue')['default']
    UserConfigPanel: typeof import('./components/settings/UserConfigPanel.vue')['default']
  }
}
